### ISSUE TITLE
Problème avec les liens de changements de filtre sur la page de recherche

### ISSUE THREAD

**Issue by brunob** [seenthis/seenthis_sphinx#3]
Si on lance une recherche avec des quotes comme ici https://seenthis.net/recherche?recherche=%22blanc+autour%22

Et qu'ensuite on tente d'élargir la recherche avec le lien "Tous les messages", alors l'url générée devient https://seenthis.net/recherche?recherche=%26quot%3Bblanc%20autour%26quot%3B&follow=all dans laquelle les quotes sont encodées, ce qui fausse complètement les résultats. Le bon lien devrait être https://seenthis.net/recherche?recherche=%22blanc+autour%22&follow=all

**Comment by brunob** [comment]
Bon, ça commence bien pour le debug, je ne reproduis pas en local, grml... Ha ben oui, forcément, je n'utilise pas sphinx en local :D

Et donc, le bug doit venir de ce que l'on passe comme paramètre `recherche` à https://github.com/seenthis/seenthis_sphinx/blob/master/sphinx2.html car en faisant du debug en prod je vois que ce squelette affiche `&quot;blanc autour&quot;` pour `#RECHERCHE*`.

**Comment by brunob** [comment]
ping @Fil & @rastapopougros sur ce coup là, je ne connais rien à ce plugin, désolé :^

**Comment by rastapopougros** [comment]
Là comme ça, ça n'a à priori rien à voir avec le plugin Indexer, qui ne s'occupe en gros que de l'indexation en PHP puis de la boucle SPHINX des résultats. Mais plutôt à voir avec les squelettes finaux utilisés, sur comment ça transmet les trucs de la query string.

On voit là que ça passe par une fonction perso : 
https://github.com/seenthis/seenthis_sphinx/blob/master/sphinx.html#L34

Qui n'est pas d'Indexer mais bien propre à Seenthis : 
https://github.com/seenthis/seenthis_sphinx/blob/master/seenthissphinx_options.php#L24

**Comment by brunob** [comment]
Après discussion sur IRC, le détail : 

```
< b_b‎ >  ha c'est fourbe
< b_b‎ >  la valeur est bonne avant de passer en tant que paramètre dans l'inclure
< b_b‎ >  nous v'là beaux
< RastaPopoulos‎ >  dès le tout début de l'inclusion sphinx2.html là c'est plus bon ?
< RastaPopoulos‎ >  c'est pas le * qui merde ?
< RastaPopoulos‎ >  avec double ** ça fait quoi ?
< b_b‎ >  	#RECHERCHE
< b_b‎ >  	#RECHERCHE*
< b_b‎ >  	#RECHERCHE**
< b_b‎ >  idem
< b_b‎ >  c'est encodé
< b_b‎ >  alors que [(#ENV*|sphinx_retraiter_env{recherche})] depuis sphinx.html est bon
< b_b‎ >  pas encodé
* b_b dégaine #PROUT
< b_b‎ >  #PROUT ok
< b_b‎ >  je le sentais
< b_b‎ >  c'est le cas de le dire :D
< b_b‎ >  spip doit agir automagiquement sur la variable recherche
< RastaPopoulos‎ >  pas de "RECHERCHE" dans les traitements auto par défaut 
< RastaPopoulos‎ >  mais un entite_html sur ENV
< RastaPopoulos‎ >  https://git.spip.net/spip/spip/src/branch/master/ecrire/public/interfaces.php#L1001
< RastaPopoulos‎ >  alors si #RECHERCHE c'est juste #ENV{recherche}
< RastaPopoulos‎ >  ya un entites_html dessus quand même
< RastaPopoulos‎ >  eeeeeh non ya carrément une définition de BALISE !
< RastaPopoulos‎ >  https://git.spip.net/spip/spip/src/branch/master/ecrire/public/balises.php#L484
< RastaPopoulos‎ >  avec de nouveau entites_html aussi dedans
< RastaPopoulos‎ >  je savais même pas…
< RastaPopoulos‎ >  perso j'utilise toujours #ENV{recherche}
< RastaPopoulos‎ >  sauf que justement là quand on met * ça supprime la table des traitements
< RastaPopoulos‎ >  donc #ENV*{recherche} ya PAS le entites_html 
< RastaPopoulos‎ >  alors que #RECHERCHE avec étoile ou pas : ça le force !
< RastaPopoulos‎ >  donc la solution c'est : utiliser #ENV et non pas #RECHERCHE pourri
< RastaPopoulos‎ >  d'ailleurs en plus le code est faux ! car #RECHERCHE va *toujours* chercher le GET ! et non pas ce qui est passé dans l'environnement depuis le parent !
< RastaPopoulos‎ >  alors que justement là dans le parent on passe explicitement recherche=un truc recalculé
< b_b‎ >  bien vu
< b_b‎ >  je teste ça
```

Donc, il ne faut pas utiliser la balise #RECHERCHE et préférer ENV{recherche}, j'envoie une PR en ce sens, testé chez moi ça fixe le bug.
